root = "."
testdata_dir = "testdata"
tmp_dir = "tmp"

[build]
  args_bin = []
  bin = "./bin/chat-app -debug=true"
  cmd = "go build -o bin/chat-app cmd/chat-app.go"
  delay = 1000
  exclude_dir = ["assets", "tmp", "vendor", "testdata", "web/dist", "internal/pkg/dist" ]
  exclude_file = ["web/htmx/**/**.go","web/htmx/**/**/**.go"]
  exclude_regex = ["_test.go"]
  exclude_unchanged = false
  follow_symlink = false
  full_bin = ""
  include_dir = ["web","internal","cmd"]
  include_ext = ["go", "tpl", "templ", "html"]
  include_file = []
  kill_delay = "0s"
  log = "build-errors.log"
  poll = false
  poll_interval = 0
  post_cmd = []
  pre_cmd = ["/Users/michel-developer/go/bin/templ generate","cd web && pnpm run build", "cp -r web/dist internal/pkg"]
  rerun = false
  rerun_delay = 1000
  send_interrupt = false
  stop_on_error = false

[color]
  app = ""
  build = "yellow"
  main = "magenta"
  runner = "green"
  watcher = "cyan"

[log]
  main_only = false
  time = false

[misc]
  clean_on_exit = false

[screen]
  clear_on_rebuild = false
  keep_scroll = true
