name: Deploy chat app to Heroku

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:

  deploy-heroku:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Build, Push and Release a Docker container to Heroku.
        uses: gonuit/heroku-docker-deploy@v1.3.3
        with:

          email: ${{ secrets.HEROKU_EMAIL }}

          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}

          heroku_app_name: ${{ secrets.HEROKU_APP_NAME }}

          docker_options: "--no-cache"
